from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG_PATH = PROJECT_ROOT / "configs" / "config.yaml"
DEFAULT_LOGGING_CONFIG_PATH = PROJECT_ROOT / "configs" / "logging.yaml"

ENV_CONFIG_PATH = "PLANTOPS_CONFIG_PATH"
ENV_LOGGING_CONFIG_PATH = "PLANTOPS_LOGGING_CONFIG_PATH"

ENV_APP_NAME = "PLANTOPS_APP_NAME"
ENV_MODEL_PATH = "PLANTOPS_MODEL_PATH"
ENV_LABEL_MAP_PATH = "PLANTOPS_LABEL_MAP_PATH"
ENV_DB_PATH = "PLANTOPS_DB_PATH"
ENV_INBOX_DIR = "PLANTOPS_INBOX_DIR"
ENV_PROCESSED_DIR = "PLANTOPS_PROCESSED_DIR"
ENV_ARCHIVE_DIR = "PLANTOPS_ARCHIVE_DIR"
ENV_REVIEW_DIR = "PLANTOPS_REVIEW_DIR"
ENV_CORRECTED_DIR = "PLANTOPS_CORRECTED_DIR"
ENV_OUTPUTS_DIR = "PLANTOPS_OUTPUTS_DIR"
ENV_LOW_CONFIDENCE_THRESHOLD = "PLANTOPS_LOW_CONFIDENCE_THRESHOLD"
ENV_LOGGING_LEVEL = "PLANTOPS_LOGGING_LEVEL"
ENV_REPORT_TIMEZONE = "PLANTOPS_REPORT_TIMEZONE"
ENV_USE_STUB_MODEL = "PLANTOPS_USE_STUB_MODEL"
